#dabase.yml

development:
  adapter: postgresql
  encoding: unicode
  database: app-pg_development
  pool: 5
  username: juan
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: app-pg_test  
  pool: 5
  username: juan
  password: 