# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4462384232dff19e75d0f6def3dae3f9cac7e2743c6ef18fb3802a61e2a25bb0044950412c122e2f0481a6896559f847c10300b1fa50f813543b343dfb0b2fcf

test:
  secret_key_base: d4effca54a0e5c7713cff540a170297f17860b7a119ae740d1d5498ac37216f7c94ebc965482487bb556a519c15ada6c1c0b67302258ef8a9dae5913170ec5bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
